name: Backend Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: |
          composer clearcache
          composer install --no-autoloader --no-scripts
          composer dump-autoload --optimize --no-dev --classmap-authoritative
      
      - name: Migrate
        run: php artisan migrate --force
            
      - name: Deploy
        run: |
          sudo apt update
          sudo apt install -y nginx
          cd /var/www/html
          git clone https://github.com/Mohamed-Dayem/Backend-laravel/tree/10.x.git
          
