name: Backend Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-7.4-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            dependencies-php-7.4-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, dom, fileinfo, filter, iconv, json, libxml, mbstring, openssl, pcntl, pcre, pdo, simplexml, sqlite, pdo_sqlite, tokenizer, xml, xmlwriter, zip

      - name: Install PHP dependencies (composer)
        run: composer install --no-interaction --no-suggest

      - name: Prepare Laravel Application
        run: cp .env.example .env

      - name: Run migration and schema dump
        run: |
          php artisan migrate --force
          php artisan schema:dump --prune
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_DATABASE: laravel
          DB_USERNAME: root
          

      - name: Deploy to production
        run: |
          sudo apt update
          sudo apt install -y nginx
          cd /var/www/html
          git clone https://github.com/Mohamed-Dayem/Backend-laravel/tree/10.x.git
          
          
